@namespace
class SpriteKind:
    EnemyTwo = SpriteKind.create()
    ExtraLife = SpriteKind.create()
@namespace
class StatusBarKind:
    EnemyTwoHealth = StatusBarKind.create()

def on_up_pressed():
    global jump
    if herosprite.is_hitting_tile(CollisionDirection.BOTTOM):
        herosprite.vy = -200
        jump = True
controller.up.on_event(ControllerButtonEvent.PRESSED, on_up_pressed)

def on_on_overlap(sprite, otherSprite):
    statusbar2.value = 100
    sprites.destroy(Extralifesprite)
sprites.on_overlap(SpriteKind.player, SpriteKind.ExtraLife, on_on_overlap)

def on_a_pressed():
    global projectile
    herosprite.set_image(img("""
        .......ff...............
        ....ffff2ff.............
        ..ffeeeef2ff............
        .ffeeeeef22ff...........
        .feeeeffeeeef...........
        .fffffee2222ef..........
        fffe222ffffe2f..........
        ffffffffeeefff..........
        fefe44ebf44eef..........
        .fee4d4bfddef...........
        ..feee4dddee.c..........
        ...f2222eeddeccccccc....
        ...f444e44ddecddddd.....
        ...fffffeeee.ccccc......
        ..ffffffff...c..........
        ..fff..ff...............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        """))
    projectile = sprites.create_projectile_from_sprite(assets.image("""
        melleee
        """), herosprite, 250, 0)
    pause(100)
    sprites.destroy(projectile)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_on_zero(status):
    sprites.destroy(status.sprite_attached_to())
statusbars.on_zero(StatusBarKind.enemy_health, on_on_zero)

def on_on_zero2(status2):
    game.game_over(False)
statusbars.on_zero(StatusBarKind.health, on_on_zero2)

def on_a_released():
    herosprite.set_image(img("""
        ........................
        .......fff..............
        ....fffff2f.............
        ..ffeeeee22ff...........
        .ffeeeeee222ff..........
        .feeeefffeeeef..........
        .fffffeee2222ef.........
        fffe222fffffe2f.........
        fffffffffeeefff.....cc..
        fefe44ebbf44eef...ccdc..
        .fee4d4bbfddef..ccddcc..
        ..feee4dddddfeecdddc....
        ...f2222222eeddcdcc.....
        ...f444445e44ddccc......
        ...ffffffffeeee.........
        ...fff...ff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        """))
controller.A.on_event(ControllerButtonEvent.RELEASED, on_a_released)

def on_on_overlap2(sprite2, otherSprite2):
    statusbar2.value += -1
sprites.on_overlap(SpriteKind.enemy, SpriteKind.player, on_on_overlap2)

def on_on_destroyed(sprite3):
    global Extralifesprite
    Extralifesprite = sprites.create(img("""
            . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . .
            . . . . . . . . . . . . . . . .
            . . 2 2 2 2 2 . . . 2 2 2 2 . .
            . 2 2 2 2 2 2 2 . 2 2 2 2 2 2 .
            . 2 2 2 2 2 2 2 . 2 2 2 2 2 2 .
            . 2 2 2 2 2 2 2 2 2 2 2 2 2 2 .
            . . 2 2 2 2 2 2 2 2 2 2 2 2 2 .
            . . . 2 2 2 2 2 2 2 2 2 2 2 . .
            . . . 2 2 2 2 2 2 2 2 2 2 2 . .
            . . . . 2 2 2 2 2 2 2 2 2 . . .
            . . . . . 2 2 2 2 2 2 2 . . . .
            . . . . . . 2 2 2 2 2 . . . . .
            . . . . . . . 2 2 2 . . . . . .
            . . . . . . . . . . . . . . . .
            """),
        SpriteKind.ExtraLife)
    tiles.place_on_random_tile(Extralifesprite, assets.tile("""
        myTile
        """))
    Extralifesprite.follow(herosprite, 50)
sprites.on_destroyed(SpriteKind.enemy, on_on_destroyed)

def on_on_overlap3(sprite4, otherSprite3):
    sprites.destroy(sprite4)
    statusbars.get_status_bar_attached_to(StatusBarKind.enemy_health, enemysprite).value += -5
sprites.on_overlap(SpriteKind.projectile, SpriteKind.enemy, on_on_overlap3)

def on_overlap_tile(sprite5, location):
    effects.blizzard.start_screen_effect()
    tiles.set_current_tilemap(tilemap("""
        level3
        """))
    herosprite.set_position(63, 125)
scene.on_overlap_tile(SpriteKind.player,
    sprites.dungeon.collectible_insignia,
    on_overlap_tile)

projectile: Sprite = None
Extralifesprite: Sprite = None
jump = False
statusbar2: StatusBarSprite = None
enemysprite: Sprite = None
herosprite: Sprite = None
game.splash("Defeat the Levels And WIN IT!")
tiles.set_current_tilemap(tilemap("""
    level0
    """))
herosprite = sprites.create(img("""
        ........................
        .......fff..............
        ....fffff2f.............
        ..ffeeeee22ff...........
        .ffeeeeee222ff..........
        .feeeefffeeeef..........
        .fffffeee2222ef.........
        fffe222fffffe2f.........
        fffffffffeeefff.....cc..
        fefe44ebbf44eef...ccdc..
        .fee4d4bbfddef..ccddcc..
        ..feee4dddddfeecdddc....
        ...f2222222eeddcdcc.....
        ...f444445e44ddccc......
        ...ffffffffeeee.........
        ...fff...ff.............
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        ........................
        """),
    SpriteKind.player)
controller.move_sprite(herosprite, 100, 0)
scene.camera_follow_sprite(herosprite)
herosprite.set_position(50, 30)
herosprite.set_stay_in_screen(True)
herosprite.ay = 200
enemysprite = sprites.create(img("""
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f11111111f.......
        ......fd11111111df......
        ......fd11111111df......
        ......fddd1111dddf......
        ......fbdbfddfbdbf......
        ......fcdcf11fcdcf......
        .......fb111111bf.......
        ......fffcdb1bdffff.....
        ....fc111cbfbfc111cf....
        ....f1b1b1ffff1b1b1f....
        ....fbfbffffffbfbfbf....
        .........ffffff.........
        ...........fff..........
        ........................
        ........................
        ........................
        ........................
        """),
    SpriteKind.enemy)
tiles.place_on_random_tile(enemysprite, assets.tile("""
    myTile
    """))
enemysprite.follow(herosprite, 80)
statusbar = statusbars.create(20, 4, StatusBarKind.enemy_health)
statusbar.attach_to_sprite(enemysprite)
statusbar2 = statusbars.create(4, 20, StatusBarKind.health)
statusbar2.attach_to_sprite(herosprite)
statusbar2.set_label("HP")
statusbar2.position_direction(CollisionDirection.LEFT)
statusbar.set_color(7, 2, 5)
statusbar.set_status_bar_flag(StatusBarFlag.SMOOTH_TRANSITION, True)